# Generated by Django 5.2.6 on 2025-10-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avtar_url",
            new_name="avatar_url",
        ),
    ]
